// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Blooduser generated by hbm2java
 */
@Entity
@Table(name = "blooduser", catalog = "hospital_system")
public class Blooduser implements java.io.Serializable {

	private String dregisteId;
	private User user;
	private String bloodType;

	public Blooduser() {
	}

	public Blooduser(User user, String bloodType) {
		this.user = user;
		this.bloodType = bloodType;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "DRegisteId", unique = true, nullable = false, length = 40)
	public String getDregisteId() {
		return this.dregisteId;
	}

	public void setDregisteId(String dregisteId) {
		this.dregisteId = dregisteId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "BloodType", nullable = false, length = 65535)
	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

}
