// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bloodhistory generated by hbm2java
 */
@Entity
@Table(name = "bloodhistory", catalog = "hospital_system")
public class Bloodhistory implements java.io.Serializable {

	private Integer id;
	private String dregisteId;
	private Integer bloodScale;
	private Date time;

	public Bloodhistory() {
	}

	public Bloodhistory(String dregisteId, Integer bloodScale, Date time) {
		this.dregisteId = dregisteId;
		this.bloodScale = bloodScale;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DRegisteId", length = 40)
	public String getDregisteId() {
		return this.dregisteId;
	}

	public void setDregisteId(String dregisteId) {
		this.dregisteId = dregisteId;
	}

	@Column(name = "BloodScale")
	public Integer getBloodScale() {
		return this.bloodScale;
	}

	public void setBloodScale(Integer bloodScale) {
		this.bloodScale = bloodScale;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
