// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Checkfactresult generated by hbm2java
 */
@Entity
@Table(name = "checkfactresult", catalog = "hospital_system")
public class Checkfactresult implements java.io.Serializable {

	private CheckfactresultId id;
	private Patienthistory patienthistory;
	private String pexamineSingleResult;
	private Date pshowResultTime;

	public Checkfactresult() {
	}

	public Checkfactresult(CheckfactresultId id, Patienthistory patienthistory, String pexamineSingleResult,
			Date pshowResultTime) {
		this.id = id;
		this.patienthistory = patienthistory;
		this.pexamineSingleResult = pexamineSingleResult;
		this.pshowResultTime = pshowResultTime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "phid", column = @Column(name = "PHId", nullable = false)),
			@AttributeOverride(name = "pexamineFact", column = @Column(name = "PExamineFact", nullable = false, length = 20)) })
	public CheckfactresultId getId() {
		return this.id;
	}

	public void setId(CheckfactresultId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHId", nullable = false, insertable = false, updatable = false)
	public Patienthistory getPatienthistory() {
		return this.patienthistory;
	}

	public void setPatienthistory(Patienthistory patienthistory) {
		this.patienthistory = patienthistory;
	}

	@Column(name = "PExamineSingleResult", nullable = false, length = 65535)
	public String getPexamineSingleResult() {
		return this.pexamineSingleResult;
	}

	public void setPexamineSingleResult(String pexamineSingleResult) {
		this.pexamineSingleResult = pexamineSingleResult;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PShowResultTime", nullable = false, length = 19)
	public Date getPshowResultTime() {
		return this.pshowResultTime;
	}

	public void setPshowResultTime(Date pshowResultTime) {
		this.pshowResultTime = pshowResultTime;
	}

}
