// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "hospital_system")
public class Doctor implements java.io.Serializable {

	private String dregisteId;
	private Entitler entitler;
	private Office office;
	private User user;

	public Doctor() {
	}

	public Doctor(User user) {
		this.user = user;
	}

	public Doctor(Entitler entitler, Office office, User user) {
		this.entitler = entitler;
		this.office = office;
		this.user = user;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "DRegisteId", unique = true, nullable = false, length = 40)
	public String getDregisteId() {
		return this.dregisteId;
	}

	public void setDregisteId(String dregisteId) {
		this.dregisteId = dregisteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEntitle")
	public Entitler getEntitler() {
		return this.entitler;
	}

	public void setEntitler(Entitler entitler) {
		this.entitler = entitler;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOfficeld")
	public Office getOffice() {
		return this.office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
