// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Eachmoney generated by hbm2java
 */
@Entity
@Table(name = "eachmoney", catalog = "hospital_system")
public class Eachmoney implements java.io.Serializable {

	private int mid;
	private float mmoney;
	private String mname;
	private Integer mtype;
	private String mcount;

	public Eachmoney() {
	}

	public Eachmoney(int mid, float mmoney) {
		this.mid = mid;
		this.mmoney = mmoney;
	}

	public Eachmoney(int mid, float mmoney, String mname, Integer mtype, String mcount) {
		this.mid = mid;
		this.mmoney = mmoney;
		this.mname = mname;
		this.mtype = mtype;
		this.mcount = mcount;
	}

	@Id

	@Column(name = "MId", unique = true, nullable = false)
	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	@Column(name = "MMoney", nullable = false, precision = 12, scale = 0)
	public float getMmoney() {
		return this.mmoney;
	}

	public void setMmoney(float mmoney) {
		this.mmoney = mmoney;
	}

	@Column(name = "Mname", length = 20)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "Mtype")
	public Integer getMtype() {
		return this.mtype;
	}

	public void setMtype(Integer mtype) {
		this.mtype = mtype;
	}

	@Column(name = "Mcount", length = 10)
	public String getMcount() {
		return this.mcount;
	}

	public void setMcount(String mcount) {
		this.mcount = mcount;
	}

}
