// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entitler generated by hbm2java
 */
@Entity
@Table(name = "entitler", catalog = "hospital_system")
public class Entitler implements java.io.Serializable {

	private int dentitle;
	private String dentitleName;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);
	private Set<Doctor> doctors_1 = new HashSet<Doctor>(0);

	public Entitler() {
	}

	public Entitler(int dentitle) {
		this.dentitle = dentitle;
	}

	public Entitler(int dentitle, String dentitleName, Set<Doctor> doctors, Set<Doctor> doctors_1) {
		this.dentitle = dentitle;
		this.dentitleName = dentitleName;
		this.doctors = doctors;
		this.doctors_1 = doctors_1;
	}

	@Id

	@Column(name = "DEntitle", unique = true, nullable = false)
	public int getDentitle() {
		return this.dentitle;
	}

	public void setDentitle(int dentitle) {
		this.dentitle = dentitle;
	}

	@Column(name = "DEntitleName", length = 10)
	public String getDentitleName() {
		return this.dentitleName;
	}

	public void setDentitleName(String dentitleName) {
		this.dentitleName = dentitleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entitler")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entitler")
	public Set<Doctor> getDoctors_1() {
		return this.doctors_1;
	}

	public void setDoctors_1(Set<Doctor> doctors_1) {
		this.doctors_1 = doctors_1;
	}

}
