// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Office generated by hbm2java
 */
@Entity
@Table(name = "office", catalog = "hospital_system")
public class Office implements java.io.Serializable {

	private int dofficeld;
	private String dofficeName;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);
	private Set<Doctor> doctors_1 = new HashSet<Doctor>(0);

	public Office() {
	}

	public Office(int dofficeld) {
		this.dofficeld = dofficeld;
	}

	public Office(int dofficeld, String dofficeName, Set<Doctor> doctors, Set<Doctor> doctors_1) {
		this.dofficeld = dofficeld;
		this.dofficeName = dofficeName;
		this.doctors = doctors;
		this.doctors_1 = doctors_1;
	}

	@Id

	@Column(name = "DOfficeld", unique = true, nullable = false)
	public int getDofficeld() {
		return this.dofficeld;
	}

	public void setDofficeld(int dofficeld) {
		this.dofficeld = dofficeld;
	}

	@Column(name = "DOfficeName", length = 20)
	public String getDofficeName() {
		return this.dofficeName;
	}

	public void setDofficeName(String dofficeName) {
		this.dofficeName = dofficeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "office")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "office")
	public Set<Doctor> getDoctors_1() {
		return this.doctors_1;
	}

	public void setDoctors_1(Set<Doctor> doctors_1) {
		this.doctors_1 = doctors_1;
	}

}
