// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patienthistory generated by hbm2java
 */
@Entity
@Table(name = "patienthistory", catalog = "hospital_system")
public class Patienthistory implements java.io.Serializable {

	private Integer phid;
	private String pregisteId;
	private Date pcomeHospitalTime;
	private int ptype;
	private String pillnessDetails;
	private String pexamineFacts;
	private String dprescription;
	private String dmedicines;
	private String dfoodSuggestion;
	private String dpreventSuggestion;
	private String dexamineResult;
	private String dregisteId;
	private Date phomeHosptial;
	private Date poutHosptial;
	private String dotherThings;
	private Integer pmoneyType;
	private String dmedicineUse;
	private Set<Checkfactresult> checkfactresults = new HashSet<Checkfactresult>(0);
	private Set<Checkfactresult> checkfactresults_1 = new HashSet<Checkfactresult>(0);

	public Patienthistory() {
	}

	public Patienthistory(String pregisteId, Date pcomeHospitalTime, int ptype, String dregisteId) {
		this.pregisteId = pregisteId;
		this.pcomeHospitalTime = pcomeHospitalTime;
		this.ptype = ptype;
		this.dregisteId = dregisteId;
	}

	public Patienthistory(String pregisteId, Date pcomeHospitalTime, int ptype, String pillnessDetails,
			String pexamineFacts, String dprescription, String dmedicines, String dfoodSuggestion,
			String dpreventSuggestion, String dexamineResult, String dregisteId, Date phomeHosptial, Date poutHosptial,
			String dotherThings, Integer pmoneyType, String dmedicineUse, Set<Checkfactresult> checkfactresults,
			Set<Checkfactresult> checkfactresults_1) {
		this.pregisteId = pregisteId;
		this.pcomeHospitalTime = pcomeHospitalTime;
		this.ptype = ptype;
		this.pillnessDetails = pillnessDetails;
		this.pexamineFacts = pexamineFacts;
		this.dprescription = dprescription;
		this.dmedicines = dmedicines;
		this.dfoodSuggestion = dfoodSuggestion;
		this.dpreventSuggestion = dpreventSuggestion;
		this.dexamineResult = dexamineResult;
		this.dregisteId = dregisteId;
		this.phomeHosptial = phomeHosptial;
		this.poutHosptial = poutHosptial;
		this.dotherThings = dotherThings;
		this.pmoneyType = pmoneyType;
		this.dmedicineUse = dmedicineUse;
		this.checkfactresults = checkfactresults;
		this.checkfactresults_1 = checkfactresults_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PHId", unique = true, nullable = false)
	public Integer getPhid() {
		return this.phid;
	}

	public void setPhid(Integer phid) {
		this.phid = phid;
	}

	@Column(name = "PRegisteId", nullable = false, length = 40)
	public String getPregisteId() {
		return this.pregisteId;
	}

	public void setPregisteId(String pregisteId) {
		this.pregisteId = pregisteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PComeHospitalTime", nullable = false, length = 19)
	public Date getPcomeHospitalTime() {
		return this.pcomeHospitalTime;
	}

	public void setPcomeHospitalTime(Date pcomeHospitalTime) {
		this.pcomeHospitalTime = pcomeHospitalTime;
	}

	@Column(name = "PType", nullable = false)
	public int getPtype() {
		return this.ptype;
	}

	public void setPtype(int ptype) {
		this.ptype = ptype;
	}

	@Column(name = "PIllnessDetails", length = 65535)
	public String getPillnessDetails() {
		return this.pillnessDetails;
	}

	public void setPillnessDetails(String pillnessDetails) {
		this.pillnessDetails = pillnessDetails;
	}

	@Column(name = "PExamineFacts", length = 20)
	public String getPexamineFacts() {
		return this.pexamineFacts;
	}

	public void setPexamineFacts(String pexamineFacts) {
		this.pexamineFacts = pexamineFacts;
	}

	@Column(name = "DPrescription", length = 65535)
	public String getDprescription() {
		return this.dprescription;
	}

	public void setDprescription(String dprescription) {
		this.dprescription = dprescription;
	}

	@Column(name = "DMedicines")
	public String getDmedicines() {
		return this.dmedicines;
	}

	public void setDmedicines(String dmedicines) {
		this.dmedicines = dmedicines;
	}

	@Column(name = "DFoodSuggestion", length = 65535)
	public String getDfoodSuggestion() {
		return this.dfoodSuggestion;
	}

	public void setDfoodSuggestion(String dfoodSuggestion) {
		this.dfoodSuggestion = dfoodSuggestion;
	}

	@Column(name = "DPreventSuggestion", length = 65535)
	public String getDpreventSuggestion() {
		return this.dpreventSuggestion;
	}

	public void setDpreventSuggestion(String dpreventSuggestion) {
		this.dpreventSuggestion = dpreventSuggestion;
	}

	@Column(name = "DExamineResult", length = 65535)
	public String getDexamineResult() {
		return this.dexamineResult;
	}

	public void setDexamineResult(String dexamineResult) {
		this.dexamineResult = dexamineResult;
	}

	@Column(name = "DRegisteId", nullable = false, length = 40)
	public String getDregisteId() {
		return this.dregisteId;
	}

	public void setDregisteId(String dregisteId) {
		this.dregisteId = dregisteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PHomeHosptial", length = 19)
	public Date getPhomeHosptial() {
		return this.phomeHosptial;
	}

	public void setPhomeHosptial(Date phomeHosptial) {
		this.phomeHosptial = phomeHosptial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "POutHosptial", length = 19)
	public Date getPoutHosptial() {
		return this.poutHosptial;
	}

	public void setPoutHosptial(Date poutHosptial) {
		this.poutHosptial = poutHosptial;
	}

	@Column(name = "DOtherThings")
	public String getDotherThings() {
		return this.dotherThings;
	}

	public void setDotherThings(String dotherThings) {
		this.dotherThings = dotherThings;
	}

	@Column(name = "PMoneyType" , nullable = false)
	public Integer getPmoneyType() {
		return this.pmoneyType;
	}

	public void setPmoneyType(Integer pmoneyType) {
		this.pmoneyType = pmoneyType;
	}

	@Column(name = "DMedicineUse", length = 65535)
	public String getDmedicineUse() {
		return this.dmedicineUse;
	}

	public void setDmedicineUse(String dmedicineUse) {
		this.dmedicineUse = dmedicineUse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patienthistory")
	public Set<Checkfactresult> getCheckfactresults() {
		return this.checkfactresults;
	}

	public void setCheckfactresults(Set<Checkfactresult> checkfactresults) {
		this.checkfactresults = checkfactresults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patienthistory")
	public Set<Checkfactresult> getCheckfactresults_1() {
		return this.checkfactresults_1;
	}

	public void setCheckfactresults_1(Set<Checkfactresult> checkfactresults_1) {
		this.checkfactresults_1 = checkfactresults_1;
	}

}
