// default package
// Generated 2018-6-3 20:03:23 by Hibernate Tools 5.2.3.Final
package niit.hospitalsys.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "hospital_system")
public class User implements java.io.Serializable {

	private String uregisteId;
	private String uid;
	private String upwd;
	private String uname;
	private String ugender;
	private Integer uage;
	private String uemail;
	private String uphone;
	private String uaddress;
	private int utype;
	private Doctor doctor;
	private Answerquestion answerquestion;
	private Blooduser blooduser;

	public User() {
	}

	public User(String uregisteId, String uid, String upwd, String uname, String ugender, String uphone, int utype) {
		this.uregisteId = uregisteId;
		this.uid = uid;
		this.upwd = upwd;
		this.uname = uname;
		this.ugender = ugender;
		this.uphone = uphone;
		this.utype = utype;
	}

	public User(String uregisteId, String uid, String upwd, String uname, String ugender, Integer uage, String uemail,
			String uphone, String uaddress, int utype, Doctor doctor, Answerquestion answerquestion,
			Blooduser blooduser) {
		this.uregisteId = uregisteId;
		this.uid = uid;
		this.upwd = upwd;
		this.uname = uname;
		this.ugender = ugender;
		this.uage = uage;
		this.uemail = uemail;
		this.uphone = uphone;
		this.uaddress = uaddress;
		this.utype = utype;
		this.doctor = doctor;
		this.answerquestion = answerquestion;
		this.blooduser = blooduser;
	}

	@Id

	@Column(name = "URegisteId", unique = true, nullable = false, length = 40)
	public String getUregisteId() {
		return this.uregisteId;
	}

	public void setUregisteId(String uregisteId) {
		this.uregisteId = uregisteId;
	}

	@Column(name = "UId", nullable = false, length = 20)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "UPwd", nullable = false, length = 40)
	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	@Column(name = "UName", nullable = false, length = 20)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "UGender", nullable = false, length = 2)
	public String getUgender() {
		return this.ugender;
	}

	public void setUgender(String ugender) {
		this.ugender = ugender;
	}

	@Column(name = "UAge")
	public Integer getUage() {
		return this.uage;
	}

	public void setUage(Integer uage) {
		this.uage = uage;
	}

	@Column(name = "UEmail", length = 20)
	public String getUemail() {
		return this.uemail;
	}

	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	@Column(name = "UPhone", nullable = false, length = 20)
	public String getUphone() {
		return this.uphone;
	}

	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	@Column(name = "UAddress", length = 100)
	public String getUaddress() {
		return this.uaddress;
	}

	public void setUaddress(String uaddress) {
		this.uaddress = uaddress;
	}

	@Column(name = "UType", nullable = false)
	public int getUtype() {
		return this.utype;
	}

	public void setUtype(int utype) {
		this.utype = utype;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Answerquestion getAnswerquestion() {
		return this.answerquestion;
	}

	public void setAnswerquestion(Answerquestion answerquestion) {
		this.answerquestion = answerquestion;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Blooduser getBlooduser() {
		return this.blooduser;
	}

	public void setBlooduser(Blooduser blooduser) {
		this.blooduser = blooduser;
	}

}
